### ISSUE TITLE
"Failed to mount devtmpfs at /dev: No such device"

### ISSUE THREAD

**Issue by emelcher** [on-prem/tinycore-kernel#1]
I compiled kernel 4.14.78. I only had to remove "firmware_install" from line 65 of the Makefile.

At boot the following message appears at the top of the screen:
"Failed to mount devtmpfs at /dev: No such device"

Is this caused by 
# CONFIG_DEVTMPFS is not set
in the .config file?
All config files in the kernels directory have CONFIG_DEVTMPFS is not set.

Should I set CONFIG_DEVTMPFS ?

**Comment by aw** [comment]
@emelcher  Sorry for the late response. Yes I tried setting `CONFIG_DEVTMPFS=y` in the `.config` file and it builds just fine.

Also, it appears since kernel `4.14.x` there is no _firmware_ in the kernel source repository.
