### ISSUE TITLE
Old hardware, trying to make this for 32 bit

### ISSUE THREAD

**Issue by dkuchay** [on-prem/tinycore-kernel#2]
Followed readme and got as far as editing the make file to aim at 32 as directed via the listed variables. Kernel downloaded but the script, make kernel, stopped a few lines in indicating that I do not have a config file for config-4.19.113-tinycore.

Is it just a matter of renaming the config? I look within and it almost looks like there is more 64 pins than the listed variables.... Is it possible to use this to build 32 bit kernels / OS? 

I have items in my hardware marked "experimental", namely cs5535 pata. Tiny is about the last micro os that has a functional build system. Would be nice to use.

**Comment by aw** [comment]
Yes you can use this to build 32-bit kernels. Just ensure:

* `kernels/config-4.19.113-tinycore` exists
* `modules/4.19.113-tinycore` exists

You can just copy the existing 64-bit version of those files/directories (and tweak the kernel config).

When you build, also specify `KERNEL_ARCH=i386` and make sure you have the `core.gz` file available in the `OSDIR` path.

**Comment by dkuchay** [comment]
Great. Thank you!
